# Generated by Django 6.0.6 on 2026-07-05 07:33

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('purchase_invoice', 'Purchase Invoice'), ('supplier_documentation', 'Supplier Documentation'), ('pdi_record', 'PDI Record'), ('warranty_documentation', 'Warranty Documentation'), ('service_documentation', 'Service Documentation'), ('diagnostic_report', 'Diagnostic Report'), ('battery_report', 'Battery Report'), ('photos', 'Photos'), ('sale_documentation', 'Sale Documentation'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=apps.documents.models.vehicle_document_upload_path, validators=[apps.documents.models.validate_document_extension])),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Document',
                'verbose_name_plural': 'Vehicle Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
