# Generated by Django 6.0.6 on 2026-07-05 07:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('childs_bike', "Child's Bike"), ('bmx', 'BMX'), ('hybrid', 'Hybrid'), ('road_bike', 'Road Bike'), ('gravel_bike', 'Gravel Bike'), ('mtb_hardtail', 'Mountain Bike - Hardtail'), ('mtb_full_suspension', 'Mountain Bike - Full Suspension'), ('tricycle', 'Tricycle'), ('adaptive_light_vehicle', 'Adaptive Light Vehicle')], max_length=30)),
                ('drive_type', models.CharField(choices=[('conventional', 'Conventional'), ('electrically_assisted', 'Electrically Assisted')], default='conventional', max_length=30)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('ex_demo', 'Ex-Demo'), ('test_bike', 'Test Bike')], default='new', max_length=20)),
                ('status', models.CharField(choices=[('acquired', 'Acquired'), ('awaiting_inspection', 'Awaiting Inspection'), ('pdi_in_progress', 'PDI In Progress'), ('preparation_required', 'Preparation Required'), ('ready_for_sale', 'Ready For Sale'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('archived', 'Archived')], default='acquired', max_length=30)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('model_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('frame_size', models.CharField(blank=True, max_length=50)),
                ('frame_material', models.CharField(blank=True, choices=[('aluminium', 'Aluminium'), ('carbon', 'Carbon'), ('steel', 'Steel'), ('titanium', 'Titanium'), ('chromoly', 'Chromoly'), ('other', 'Other')], max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recommended_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('frame_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('fork_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('drivetrain_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('wheels_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('brakes_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('suspension_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('electrical_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('estimated_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preparation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_performed', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='used_assessment', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Used Vehicle Assessment',
                'verbose_name_plural': 'Used Vehicle Assessments',
            },
        ),
        migrations.CreateModel(
            name='ElectricVehicleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_manufacturer', models.CharField(blank=True, max_length=100)),
                ('motor_serial_number', models.CharField(blank=True, max_length=100)),
                ('battery_serial_number', models.CharField(blank=True, max_length=100)),
                ('charger_serial_number', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('diagnostic_notes', models.TextField(blank=True)),
                ('battery_health_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_diagnostic_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electric_detail', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Electric Vehicle Detail',
                'verbose_name_plural': 'Electric Vehicle Details',
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['company', 'status'], name='vehicles_ve_company_9aff87_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['stock_number'], name='vehicles_ve_stock_n_68def6_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['serial_number'], name='vehicles_ve_serial__813fd4_idx'),
        ),
    ]
