# Generated by Django 6.0.6 on 2026-07-05 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('layer', models.CharField(choices=[('universal', 'Universal (All Vehicles)'), ('vehicle_type', 'Vehicle Type Specific'), ('electric', 'Electric Vehicle'), ('manufacturer', 'Manufacturer Specific')], max_length=20)),
                ('vehicle_type', models.CharField(blank=True, choices=[('childs_bike', "Child's Bike"), ('bmx', 'BMX'), ('hybrid', 'Hybrid'), ('road_bike', 'Road Bike'), ('gravel_bike', 'Gravel Bike'), ('mtb_hardtail', 'Mountain Bike - Hardtail'), ('mtb_full_suspension', 'Mountain Bike - Full Suspension'), ('tricycle', 'Tricycle'), ('adaptive_light_vehicle', 'Adaptive Light Vehicle')], help_text='Leave blank for universal templates', max_length=30)),
                ('drive_type', models.CharField(blank=True, choices=[('conventional', 'Conventional'), ('electrically_assisted', 'Electrically Assisted')], help_text='Leave blank for non-drive-specific templates', max_length=30)),
                ('motor_manufacturer', models.CharField(blank=True, help_text='e.g. Bosch, Shimano Steps, Mahle', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDI Template',
                'verbose_name_plural': 'PDI Templates',
                'ordering': ['layer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PDIInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('overall_result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdi_inspections', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdi_inspections', to='vehicles.vehicle')),
                ('templates_applied', models.ManyToManyField(blank=True, related_name='inspections', to='pdi.pditemplate')),
            ],
            options={
                'verbose_name': 'PDI Inspection',
                'verbose_name_plural': 'PDI Inspections',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PDISignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('signature_name', models.CharField(help_text="Technician's printed name", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdi_approvals', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sign_off', to='pdi.pdiinspection')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdi_sign_offs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDI Sign-Off',
                'verbose_name_plural': 'PDI Sign-Offs',
            },
        ),
        migrations.CreateModel(
            name='PDITemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(help_text='e.g. Safety, Assembly, Functional', max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('guidance', models.TextField(blank=True, help_text='Technician guidance notes')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pdi.pditemplate')),
            ],
            options={
                'verbose_name': 'PDI Template Item',
                'verbose_name_plural': 'PDI Template Items',
                'ordering': ['section', 'order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='PDIInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pdi.pdiinspection')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_items', to='pdi.pditemplateitem')),
            ],
            options={
                'verbose_name': 'PDI Inspection Item',
                'verbose_name_plural': 'PDI Inspection Items',
                'ordering': ['template_item__section', 'template_item__order'],
            },
        ),
    ]
